ALTER TABLE users
ADD COLUMN IF NOT EXISTS cbu TEXT;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS cbu_hash VARCHAR(64);

ALTER TABLE users
ADD COLUMN IF NOT EXISTS email_hash VARCHAR(64);

ALTER TABLE users
ADD COLUMN IF NOT EXISTS nickname_hash VARCHAR(64);

UPDATE users
SET cbu = '0000000000000000000000'
WHERE cbu IS NULL;

ALTER TABLE users
ALTER COLUMN cbu SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS users_cbu_hash_key
ON users (cbu_hash)
WHERE cbu_hash IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS users_email_hash_key
ON users (email_hash)
WHERE email_hash IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS users_nickname_hash_key
ON users (nickname_hash)
WHERE nickname_hash IS NOT NULL;
